version: "2"

linters:
  default: none
  enable:
    - govet
    - errcheck
    - staticcheck
    - revive
    - unused

formatters:
  enable:
    - gofumpt
  settings:
    gofumpt:
      module-path: github.com/littlebugger/bifrost
