package smtpdrv

import (
	"fmt"
	"strings"
	"testing"

	"github.com/revolee/bifrost/internal/fakesmtp"
)

func TestDrvExpectMultiline(t *testing.T) {
	srv := fakesmtp.Start(t, fakesmtp.Script{Caps: []string{"PIPELINING", "8BITMIME"}})
	c := Dial(t, srv.Addr())
	c.Expect("220")

	c.Send("EHLO client.example")
	reply := c.Expect("250")

	joined := strings.Join(reply.Lines, "\n")
	if !strings.Contains(joined, "PIPELINING") || !strings.Contains(joined, "8BITMIME") {
		t.Fatalf("EHLO reply = %v, want caps PIPELINING and 8BITMIME", reply.Lines)
	}
	if len(reply.Lines) < 2 {
		t.Fatalf("EHLO reply = %v, want a fully captured multiline reply", reply.Lines)
	}
}

func TestDrvPipelineExpectN(t *testing.T) {
	srv := fakesmtp.Start(t, fakesmtp.Script{})
	c := Dial(t, srv.Addr())
	c.Expect("220")
	c.Send("EHLO client.example")
	c.Expect("250")

	c.Pipeline(
		"MAIL FROM:<a@b>",
		"RCPT TO:<c@d>",
		"RCPT TO:<e@f>",
		"DATA",
	)
	replies := c.ExpectN("250", "250", "250", "354")
	if len(replies) != 4 {
		t.Fatalf("ExpectN returned %d replies, want 4", len(replies))
	}
}

func TestDrvRawViolation(t *testing.T) {
	srv := fakesmtp.Start(t, fakesmtp.Script{})
	c := Dial(t, srv.Addr())
	c.Expect("220")

	c.Raw([]byte("EHLO client.example\n")) // bare LF, no CR: a protocol violation
	c.Expect("250")

	sessions := srv.Sessions()
	if len(sessions) != 1 {
		t.Fatalf("Sessions() len = %d, want 1", len(sessions))
	}
	events := sessions[0].Transcript()
	if len(events) != 1 {
		t.Fatalf("Transcript() len = %d, want 1", len(events))
	}
	want := "EHLO client.example\n"
	if string(events[0].Line) != want {
		t.Fatalf("recorded line = %q, want %q (raw, bare LF preserved as sent)", events[0].Line, want)
	}
}

func TestDrvSendMsg(t *testing.T) {
	srv := fakesmtp.Start(t, fakesmtp.Script{})
	c := Dial(t, srv.Addr())
	c.Expect("220")
	c.Send("EHLO client.example")
	c.Expect("250")

	reply := c.SendMsg(7)
	if reply.Code[0] != '2' {
		t.Fatalf("SendMsg verdict = %v, want 2xx", reply.Lines)
	}

	wantBody := fmt.Sprintf("Subject: message %d\r\n\r\nbody %d\r\n", 7, 7)
	srv.AssertWireBody(t, 0, []byte(wantBody))

	// fakesmtp.Msg.From/Rcpts hold raw wire text (keyword + params
	// included), not a parsed address — assert the exact documented
	// format once here.
	msgs := srv.Sessions()[0].Messages()
	if len(msgs) != 1 {
		t.Fatalf("Messages() len = %d, want 1", len(msgs))
	}
	if want := "FROM:<sender7@test.example>"; msgs[0].From != want {
		t.Errorf("From = %q, want %q (raw wire text, keyword included)", msgs[0].From, want)
	}
	if want := "TO:<rcpt7@test.example>"; len(msgs[0].Rcpts) != 1 || msgs[0].Rcpts[0] != want {
		t.Errorf("Rcpts = %v, want [%q]", msgs[0].Rcpts, want)
	}
}

// TestSendMsgRespectsDataRefusal proves SendMsg never writes the DATA
// body when DATA itself was refused (a non-3yz reply), even with a
// non-aborting SetFail reporter installed: the body must not be written
// (the fake never sees a complete message), and the session must stay
// in sync (the next command gets a normal reply, not a leftover "500"
// generated by the fake misreading an unsolicited body as commands).
func TestSendMsgRespectsDataRefusal(t *testing.T) {
	srv := fakesmtp.Start(t, fakesmtp.Script{
		OnDATA: []fakesmtp.Step{{Reply: "451 4.3.2 too busy"}},
	})
	c := Dial(t, srv.Addr())
	c.Expect("220")
	c.Send("EHLO client.example")
	c.Expect("250")

	var got string
	c.SetFail(func(format string, args ...any) {
		got = fmt.Sprintf(format, args...)
	})

	reply := c.SendMsg(0)
	if reply.Code != "451" {
		t.Fatalf("SendMsg verdict = %v, want [451 ...] (DATA's own refusal, not the end-of-data reply)", reply.Lines)
	}
	if got == "" {
		t.Fatalf("SetFail callback was never invoked for the DATA mismatch")
	}

	sessions := srv.Sessions()
	if len(sessions) != 1 {
		t.Fatalf("Sessions() len = %d, want 1", len(sessions))
	}
	if msgs := sessions[0].Messages(); len(msgs) != 0 {
		t.Fatalf("Messages() len = %d, want 0: DATA was refused, so no body should ever have been sent", len(msgs))
	}

	// Still in sync: the fake reads this as the next command, not as
	// leftover body-turned-garbage from an unsolicited write.
	c.Send("RSET")
	if next := c.Expect("2"); next.Code[0] != '2' {
		t.Fatalf("RSET after refused DATA = %v, want 2xx (session desynced by an unsolicited body)", next.Lines)
	}
}

func TestDrvAbortMidData(t *testing.T) {
	srv := fakesmtp.Start(t, fakesmtp.Script{})
	c := Dial(t, srv.Addr())
	c.Expect("220")
	c.Send("EHLO client.example")
	c.Expect("250")

	c.AbortMidData(20)

	sessions := srv.Sessions()
	if len(sessions) != 1 {
		t.Fatalf("Sessions() len = %d, want 1", len(sessions))
	}
	if msgs := sessions[0].Messages(); len(msgs) != 0 {
		t.Fatalf("Messages() len = %d, want 0: the backend must see EOF before the terminator, never completing the message", len(msgs))
	}
}

// TestDrvSetFail proves the escape hatch actually redirects failure
// reporting: with a custom (non-aborting) fail func installed, a
// deliberate mismatch invokes it instead of failing the test via
// testing.TB.Fatalf.
func TestDrvSetFail(t *testing.T) {
	srv := fakesmtp.Start(t, fakesmtp.Script{})
	c := Dial(t, srv.Addr())

	var got string
	c.SetFail(func(format string, args ...any) {
		got = fmt.Sprintf(format, args...)
	})

	c.Expect("999") // banner is 220: deliberately wrong prefix

	if got == "" {
		t.Fatalf("SetFail callback was never invoked")
	}
	if !strings.Contains(got, "999") {
		t.Errorf("fail message = %q, want it to mention the wanted prefix 999", got)
	}
}

func TestDrvStartTLS(t *testing.T) {
	cfg := fakesmtp.TestCert(t)
	srv := fakesmtp.Start(t, fakesmtp.Script{TLS: cfg})
	c := Dial(t, srv.Addr())
	c.Expect("220")

	c.Send("EHLO client.example")
	reply := c.Expect("250")
	if !strings.Contains(strings.Join(reply.Lines, "\n"), "STARTTLS") {
		t.Fatalf("EHLO reply = %v, want STARTTLS advertised", reply.Lines)
	}

	c.StartTLS(cfg)

	c.Send("EHLO client.example")
	reply2 := c.Expect("250")
	if strings.Contains(strings.Join(reply2.Lines, "\n"), "STARTTLS") {
		t.Fatalf("EHLO reply over TLS = %v, want STARTTLS no longer advertised", reply2.Lines)
	}

	c.Send("QUIT")
	c.Expect("221")
}
